CourseWork/Models/DutyOfEngineerViewModel.cs
using System;

namespace CourseWork.Models
{
    public class DutyOfEngineerViewModel
    {
        public Guid EngineerId { get; set; }
        
        public string ClassCipher { get; set; }
        
        public DateTime DutyDate { get; set; }
        
        public int NumberOfFaults { get; set; }
    }
}

CourseWork/Models/ErrorViewModel.cs
using System;

namespace CourseWork.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CourseWork/Controllers/DutiesOfEngineerController.cs
using System;
using System.Threading.Tasks;
using CourseWork.Application.Services.Interfaces;
using CourseWork.Domain.Domain;
using CourseWork.Models;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers
{
    [Route("[controller]/[action]")]
    public class DutiesOfEngineerController : Controller
    {
        private readonly IDutyService _dutyService;

        public DutiesOfEngineerController(IDutyService dutyService)
        {
            _dutyService = dutyService;
        }

        [HttpPost]
        public async Task<IActionResult> CreateDutyRecord(DutyOfEngineerViewModel model)
        {
            model.EngineerId = Guid.NewGuid();
            await _dutyService.Create(new DutyOfEngineer()
            {
                EngineerId = model.EngineerId,
                ClassCipher = model.ClassCipher,
                NumberOfFaults = model.NumberOfFaults,
                DutyDate = model.DutyDate
            });
            return Redirect("/Home/Index");
        }
    }
}

CourseWork/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CourseWork.Models;

namespace CourseWork.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CourseWork/Views/Home/Index.cshtml
@model CourseWork.Models.DutyOfEngineerViewModel
@{
    ViewData["Title"] = "DutyOfEngineerViewModel";
}

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
     aria-hidden="true" xmlns="http://www.w3.org/1999/html">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Добавить дежурство инженера</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      @using(Html.BeginForm("CreateDutyRecord","DutiesOfEngineer"))
      {
      <div class="modal-body">
          <input type="text" name="EngineerId" />
          <input type="text" name="ClassCipher" />
          <input type="text" name="DutyDate" />
          <input type="text" name="NumberOfFaults" />
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
          <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
      }
    </div>
  </div>
</div>

<div class="add-duty-button" data-toggle="modal" data-target="#exampleModalLong">
  <button type="button" class="btn btn-light">+ Add</button>
</div>

<div class="dutyTable">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@@mdo</td>
        <td><button type="button" class="btn btn-outline-success">Success</button></td>
        <td><button type="button" class="btn btn-outline-danger">Danger</button></td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@@fat</td>
        <td><button type="button" class="btn btn-outline-success">Success</button></td>
        <td><button type="button" class="btn btn-outline-danger">Danger</button></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Larry</td>
        <td>the Bird</td>
        <td>@@twitter</td>
        <td><button type="button" class="btn btn-outline-success">Success</button></td>
        <td><button type="button" class="btn btn-outline-danger">Danger</button></td>
      </tr>
    </tbody>
  </table>
</div>

CourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CourseWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseWork</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - CourseWork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>